name: aws_auth
description: Low-level library for signing AWS API requests.
homepage: https://github.com/jakub-bacic/aws_auth

version: 2.0.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  collection: ^1.15.0
  convert: ^3.0.0
  crypto: ^3.0.0
  intl: ^0.17.0

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.14.4
  test_coverage: ^0.5.0
