name: aws_auth
description: Low-level library for signing AWS API requests.
homepage: https://github.com/jakub-bacic/aws_auth

version: 1.0.0+1

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  collection: ^1.14.13
  convert: ^2.1.1
  crypto: ^2.1.5
  intl: ^0.16.1

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
  test_coverage: ^0.5.0
