name: CI

on:
  # Run on PRs and pushes to the default branch.
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: "0 0 * * 0"

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: 'stable'
      - id: install
        name: Install dependencies
        run: dart pub get
      - name: Check formatting
        run: dart format --output=none --set-exit-if-changed .
      - name: Analyze code
        run: dart analyze --fatal-infos

  test:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: 'stable'
      - id: install
        name: Install dependencies
        run: dart pub get
      - name: Run tests
        run: dart test
      - name: Test coverage
        run: dart pub run test_coverage
      - name: Upload coverage to Codecov 
        uses: codecov/codecov-action@v1

  docs-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: 'stable'
      - name: Generate docs
        run: dartdoc --errors unresolved-doc-reference
      - name: Deploy to Netlify
        if: ${{ github.event_name == 'pull_request' }}
        id: netlify
        uses: nwtgck/actions-netlify@v1.1
        with:
          publish-dir: './doc/api'
          deploy-message: ${{ github.event.pull_request.head.sha }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          production-deploy: false
          enable-pull-request-comment: false
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1
      - name: Comment on PR
        if: ${{ github.event_name == 'pull_request' }}
        uses: actions/github-script@v3
        with:
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '📝 Docs preview for commit ${{ github.event.pull_request.head.sha }} available at: ${{ steps.netlify.outputs.deploy-url }}'
            })
